from mypkg.my2DPlot import my2DPlot
from mypkg.Iteration1D import Iteration1D
from mypkg.prini import prini
from mypkg.aitkens import Aitkens
from mypkg.steffensons import Steffensons
from mypkg.newtons import Newtons
from mypkg.secant import Secant
from mypkg.newtons_nonlinear import NewtonsNonlinear
from mypkg.steepest_descent import SteepestDescent
from mypkg.interp import Interp
from mypkg.splines import Splines
from mypkg.quadrature import Quad